version: '3.7'

services:
  orange-api:
    build:
      context: ./orange-go
      dockerfile: Dockerfile
      args:
        image: Api
    image: orange-api
    container_name: orange-api
    ports:
      - "8001:8080"