broker: redis://localhost:6379/1 #redis://[password@]host[port][/db_num]
default_queue: "queue"
result_backend: redis://localhost:6379/1
results_expire_in: 259200 #结果过期时间
redis:
  max_idle: 3
  max_active: 3
  max_idle_timeout: 240
  wait: true
  read_timeout: 15
  write_timeout: 15
  connect_timeout: 15
  normal_tasks_poll_period: 1000
  delayed_tasks_poll_period: 500
  delayed_tasks_key: "queue"